[project]
name = 'Blockchain-Based-Cross-Border-Identity-Verification'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.audit-trail]
path = 'contracts/audit-trail.clar'
clarity_version = 2
epoch = 2.5

[contracts.compliance]
path = 'contracts/compliance.clar'
clarity_version = 2
epoch = 2.5

[contracts.identity-provider]
path = 'contracts/identity-provider.clar'
clarity_version = 2
epoch = 2.5

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
